In [3]:
import ml_collections
# 创建一个类似于字典的类
# ML Collections是为ML use cases而设计的一个Python Collections的一个库。
# 它的两个类是ConfigDict和FrozenConfigDict，是"dict-like" 的数据结构
#通过.add_name即可添加数据。
#由于是type_safe的，新的赋值需要与上一次赋值的类相同（原来是int的，只能再赋值为int型）

cfg = ml_collections.ConfigDict()
cfg.float_field = 12.6
cfg.integer_field = 123
cfg.another_integer_field = 234
cfg.nested = ml_collections.ConfigDict()
cfg.nested.string_field = 'tom'

print(cfg)

another_integer_field: 234
float_field: 12.6
integer_field: 123
nested:
  string_field: tom



In [6]:
import torch
x1 = torch.randn([1,3,2,2])
print(x1)
x2 = torch.randn([1,3,2,2])
print(x2)
x3 = torch.cat([x1,x2],dim=3)
print(x3.shape, '\n', x3)

tensor([[[[-0.5936, -1.5723],
          [-0.9907, -0.6394]],

         [[-0.5378,  0.8907],
          [ 0.3812,  0.2824]],

         [[-0.4175,  0.1793],
          [-2.1888,  0.9633]]]])
tensor([[[[-5.1354e-01, -1.1622e-01],
          [ 1.3802e-01,  5.5687e-01]],

         [[-1.5240e+00,  3.7857e-01],
          [ 9.5743e-01,  7.4992e-04]],

         [[-1.5583e+00, -3.4195e-01],
          [-2.4634e+00, -1.0152e+00]]]])
torch.Size([1, 3, 2, 4]) 
 tensor([[[[-5.9360e-01, -1.5723e+00, -5.1354e-01, -1.1622e-01],
          [-9.9071e-01, -6.3936e-01,  1.3802e-01,  5.5687e-01]],

         [[-5.3776e-01,  8.9073e-01, -1.5240e+00,  3.7857e-01],
          [ 3.8120e-01,  2.8243e-01,  9.5743e-01,  7.4992e-04]],

         [[-4.1749e-01,  1.7929e-01, -1.5583e+00, -3.4195e-01],
          [-2.1888e+00,  9.6325e-01, -2.4634e+00, -1.0152e+00]]]])


In [8]:
import torch
import torch.nn as nn
input = torch.arange(1, 9, dtype=torch.float32).view(1, 1, 2, 4)
input

tensor([[[[1., 2., 3., 4.],
          [5., 6., 7., 8.]]]])

In [10]:
m = nn.UpsamplingBilinear2d(size=(4,4))
m(input)

tensor([[[[1.0000, 2.0000, 3.0000, 4.0000],
          [2.3333, 3.3333, 4.3333, 5.3333],
          [3.6667, 4.6667, 5.6667, 6.6667],
          [5.0000, 6.0000, 7.0000, 8.0000]]]])

In [13]:
li = [None]
li.append(None)
li

[None, None]

In [1]:
import torch
import torch.nn as nn
class MODEL(nn.Module):
    def __init__(self) -> None:
        super().__init__()
        self.layer1=nn.Sequential(
            nn.Conv2d(512,32,3),
            nn.Linear(32,10),
        )
        self.layer2 = nn.ReLU()
    def forward(self, x):
        x = self.layer1(x)
        x = nn.MaxPool2d((1,1),(1,1),1)(x)
        x = self.layer2(x)
        return x


net = MODEL()
for name, node in net.named_children():
    print(name,'\n')
    for named, noded in node.named_children():
        print(name,'\n')
print(net)

layer1 

layer1 

layer1 

layer2 

MODEL(
  (layer1): Sequential(
    (0): Conv2d(512, 32, kernel_size=(3, 3), stride=(1, 1))
    (1): Linear(in_features=32, out_features=10, bias=True)
  )
  (layer2): ReLU()
)


d:\anaconda3\envs\TransUnet\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
import torch
import torch.nn as nn
input = torch.arange(1, 5, dtype=torch.float32).view(1, 1, 2, 2)
print(input)
m = nn.UpsamplingBilinear2d(size=(2,2))
m(input)


tensor([[[[1., 2.],
          [3., 4.]]]])


tensor([[[[1., 2.],
          [3., 4.]]]])

In [10]:
import matplotlib.pyplot as plt
import nibabel as nib
img_arr = nib.load('../simpleitk_save.nii.gz')
print(img_arr)
#img_arr = img_arr[:,:,-1]
#plt.imshow(img_arr)
# plt.pause(3)

<class 'nibabel.nifti1.Nifti1Image'>
data shape (512, 512, 100)
affine: 
[[-1.  0.  0. -0.]
 [ 0. -1.  0. -0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
metadata:
<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 0
session_error   : 0
regular         : b'r'
dim_info        : 0
dim             : [  3 512 512 100   1   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : int16
bitpix          : 16
slice_start     : 0
pixdim          : [1. 1. 1. 1. 0. 0. 0. 0.]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 2
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 0
glmin           : 0
descrip         : b''
aux_file        : b''
qform_code      : scanner
sform_code      : scanner
quatern_b       : 0.0
quater

In [9]:
import SimpleITK as sitk
import numpy as np
itk_img = sitk.ReadImage('../case0038_gt.nii.gz')
img = sitk.GetArrayFromImage(itk_img)
out = img.astype(np.int16)
out = sitk.GetImageFromArray(out)
sitk.WriteImage(out,'../simpleitk_save.nii.gz')